### ISSUE TITLE
Changed paths to your directories

### ISSUE THREAD

**Issue by loknjinu13** [jumpingcontent/week8#2]
Line 12, 
mkdir ~/gitstuff
Line 15,/line 52...
cd ~/gitstuff

line 71 to 77
mkdir ~/first_one ~/first_two
echo "first one here!" > ~/first_one/1st
echo "second one here!" > ~/first_one/2nd
echo "third one here!" > ~/first_one/3rd
echo "fourth one here" > ~/first_two/4th
ln ~/first_one/3rd ~/first_two/5th
ls -iR ~/first_*

**Comment by loknjinu13** [comment]
Great work...learnt alot 
check out your mkfs file creation too

**Comment by jumpingcontent** [comment]
Thanks for the input! I edited some changes to make the directories more precise and mkfs also mount.
